package com.blackknightdemo.dmnrulesdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocProcessUtil implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DocProcessUtil() {
    }




}