package com.blackknightdemo.dmnrulesdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

import javax.xml.namespace.NamespaceContext;
import java.util.Map;
import java.util.HashMap;
import java.util.Iterator;

public class SimpleNamespaceContext implements NamespaceContext{
    
    private final Map<String, String> PREF_MAP = new HashMap<String, String>();

    public SimpleNamespaceContext(final Map<String, String> prefMap) {
        PREF_MAP.putAll(prefMap);       
    }

    public String getNamespaceURI(String prefix) {
        System.out.println("Using Prefix : "  + prefix + " = "+ PREF_MAP.get(prefix));
        return PREF_MAP.get(prefix);
    }

    public String getPrefix(String uri) {
        throw new UnsupportedOperationException();
    }

    public Iterator getPrefixes(String uri) {
        throw new UnsupportedOperationException();
    }

}
