package com.blackknightdemo.dmnrulesdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimpleNamespaceContext implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SimpleNamespaceContext() {
    }




}